version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  ignore:
    # ignore Maven Core updates
    - dependency-name: "org.apache.maven:*"
  open-pull-requests-limit: 10
