# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: ./mvnw --batch-mode verify
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Test Results
        path: |
            target/surefire-reports/TEST*.xml
            target/failsafe-reports/TEST*.xml
    - name: Publish Code Coverage in PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 55
        min-coverage-changed-files: 70
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'mojohaus/buildplan-maven-plugin' && github.actor != 'dependabot[bot]'
    - name: Build documentation
      run: ./mvnw --batch-mode site
  event_file:
    name: "Publish event file"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}
